### ISSUE TITLE
Unable to find docs 

### ISSUE THREAD

**Issue by adirshaban** [torodb/torodb#79]
Hi,

I can't find the docs anywhere, and im getting exception:

```
Exception in thread "main" java.lang.IllegalArgumentException /protocol/mongo/replication: instance type (null)
```
when i tried to changed it from null to an empty array i got another exception.
I dont want to use replications yet, where can i see some docs?

**Comment by teoincontatto** [comment]
Hi @adirshaban,

The /protocol/mongo/replication section is optional and does not need to be specified. The error is due to torodb thinking that the configuration is not correctly set for replication. You should remove or comment out the /protocol/mongo/replication section from configuration file to disable it.

Anyway you can find configuration documentation [here on torodb's github](https://github.com/torodb/torodb/wiki/Installation-guide#torodbs-configuration).

**Comment by ahachete** [comment]
Hi @adirshaban 

If you are not going to use replication, simply omit the field from the YAML file. That should work. Please also review the documentation on these parameters, as @teoincontatto suggested.

Having said this, the default config generates a YAML file that should not contain a null value in the replication field. I will close this issue (please reopen it if you consider it didn't help you), but opened issue #80
